version: '2'
services:
  reporter1:
    build: 
      context: .
    image: "reporter:v1"
    container_name: reporter1
    volumes:
      - /storagepool/ibc/env-commands:/env-commands
    dns:
      - 10.0.0.7
    networks:
      reporter:
        ipv4_address: 10.0.0.180
  reporter2:
    build: 
      context: .
    image: "reporter:v1"
    container_name: reporter2
    volumes:
      - /storagepool/ibc/env-commands:/env-commands
    dns:
      - 10.0.0.7
    networks:
      reporter:
        ipv4_address: 10.0.0.181
  reporter3:
    build: 
      context: .
    image: "reporter:v1"
    container_name: reporter3
    volumes:
      - /storagepool/ibc/env-commands:/env-commands
    dns:
      - 10.0.0.7
    networks:
      reporter:
        ipv4_address: 10.0.0.182
networks:
  reporter:
    #external: true
    driver: macvlan
    driver_opts:
      parent: enp1s0f0
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.7