version: '2'
services:
  reporter1:
    command: "/bin/bash -c /home/node/app/reporter/run.sh"
    build: 
      context: .
    image: "reporter:v1"
    container_name: reporter1
    volumes:
      - /storagepool/ibc/env-commands:/home/node/app/reporter
  reporter2:
    command: "/bin/bash -c /home/node/app/reporter/run.sh"
    build: 
      context: .
    image: "reporter:v1"
    container_name: reporter2
    volumes:
      - /storagepool/ibc/env-commands2:/home/node/app/reporter
  reporter3:
    command: "/bin/bash -c /home/node/app/reporter/run.sh"
    build: 
      context: .
    image: "reporter:v1"
    container_name: reporter3
    volumes:
      - /storagepool/ibc/env-commands3:/home/node/app/reporter
